mod = RegisterMod("modd", 1)

local game = Game()
include("items/fart")
include("items/mega_statup")
include("characters/character1")
include("items/active_Healer")
include("mirrored_mines/stage")
include("mirrored_mines/genRoom")
include("mirrored_mines/trapdoor")
